apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gunicorn-deployment
spec:
  selector:
    matchLabels:
      app: flask-gunicorn
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-gunicorn
    spec:
      containers:
      - name: flask-gunicorn
        image: gcr.io/<project_id>/flask-gunicorn:v1.2
        ports:
        - containerPort: 8000
        env:
        - name: "ENV"
          value: "GKE" 
        imagePullPolicy: Always