apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gunicorn-deployment
spec:
  selector:
    matchLabels:
      app: flask-gunicorn
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-gunicorn
    spec:
      containers:
      - name: flask-gunicorn
        image: [aws_account_id].dkr.ecr.us-east-2.amazonaws.com/flask-python:v1.5
        ports:
        - containerPort: 8000
        env:
        - name: "ENV"
          value: "EKS" 
        imagePullPolicy: Always