apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gunicorn-deployment
spec:
  selector:
    matchLabels:
      app: flask-gunicorn
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-gunicorn
    spec:
      containers:
      - name: flask-gunicorn
        image: docker.io/library/flask-gunicorn:2023-01-21
        ports:
        - containerPort: 8000
        env:
        - name: "ENV"
          value: "minikube"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 
        imagePullPolicy: Never